#https://mherman.org/blog/dockerizing-a-react-app/

version: '3.7'
services:
  webserver:
    build:
      context: .
      dockerfile: webserver.dev.Dockerfile
    volumes:
      - './VTCheckWebsite:/app'
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  apiserver:
    build:
      context: .
      dockerfile: apiserver.dev.Dockerfile
    volumes:
      - './VTCheckSVC:/app'
    ports:
      - 5001:5000
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./VTCheckSVC/SQL_Scripts:/app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123'